//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on/off auto locking of windows\nAuto lock window.
        /// </summary>
        public static string BTN_HLP_AUTOLOCK_WINDOWS {
            get {
                return ResourceManager.GetString("BTN_HLP_AUTOLOCK_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone active window\nClone window.
        /// </summary>
        public static string BTN_HLP_CLONE_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_CLONE_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close active window\nClose window.
        /// </summary>
        public static string BTN_HLP_CLOSE_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_CLOSE_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock active window from closing\nLock window.
        /// </summary>
        public static string BTN_HLP_LOCK_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_LOCK_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore closed window\nRestore closed window.
        /// </summary>
        public static string BTN_HLP_RESTORE_CLOSED_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_RESTORE_CLOSED_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock active window from closing\nUnlock window.
        /// </summary>
        public static string BTN_HLP_UNLOCK_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_UNLOCK_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore windows.
        /// </summary>
        public static string DLG_TTL_RESTORE_WINDOWS {
            get {
                return ResourceManager.GetString("DLG_TTL_RESTORE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick window to restore.
        /// </summary>
        public static string DLG_TXT_PICK_WINDOW_TO_RESTORE {
            get {
                return ResourceManager.GetString("DLG_TXT_PICK_WINDOW_TO_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no windows to restore!.
        /// </summary>
        public static string ERR_NO_WINDOWS_TO_RESTORE {
            get {
                return ResourceManager.GetString("ERR_NO_WINDOWS_TO_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About {0}....
        /// </summary>
        public static string MNU_ABOUT_PROGRAM {
            get {
                return ResourceManager.GetString("MNU_ABOUT_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;End program.
        /// </summary>
        public static string MNU_END_PROGRAM {
            get {
                return ResourceManager.GetString("MNU_END_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string MNU_HELP {
            get {
                return ResourceManager.GetString("MNU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore one or more windows closed during this session.
        /// </summary>
        public static string MNU_HLP_RESTORE_CLOSED_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_HLP_RESTORE_CLOSED_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which windows automatically to store positions of.
        /// </summary>
        public static string MNU_HLP_STORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("MNU_HLP_STORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically show the Layer Control window on startup.
        /// </summary>
        public static string MNU_HLP_TOGGLE_SHOW_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_SHOW_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore closed window....
        /// </summary>
        public static string MNU_RESTORE_CLOSED_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_RESTORE_CLOSED_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;all windows.
        /// </summary>
        public static string MNU_SHOW_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_SHOW_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the &amp;Info window.
        /// </summary>
        public static string MNU_SHOW_INFO_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_INFO_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the &amp;Legend window.
        /// </summary>
        public static string MNU_SHOW_LEGEND_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_LEGEND_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Map&amp;Basic window.
        /// </summary>
        public static string MNU_SHOW_MAPBASIC_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_MAPBASIC_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the &amp;Message window.
        /// </summary>
        public static string MNU_SHOW_MESSAGE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_MESSAGE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the &amp;Ruler window.
        /// </summary>
        public static string MNU_SHOW_RULER_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_RULER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the &amp;Statistics window.
        /// </summary>
        public static string MNU_SHOW_STATISTICS_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_STATISTICS_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show window.
        /// </summary>
        public static string MNU_SHOW_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Auto store position of windows.
        /// </summary>
        public static string MNU_STORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("MNU_STORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Layer Control on startup.
        /// </summary>
        public static string MNU_TOGGLE_SHOW_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_SHOW_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowHelper can store size and position of windows on exit and restore these windows when it starts up next time. {\n}{\n}Do you want to turn this on?.
        /// </summary>
        public static string QUEST_AUTOSTORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("QUEST_AUTOSTORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to close this window: {0} ?.
        /// </summary>
        public static string QUEST_CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("QUEST_CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string STR_NO {
            get {
                return ResourceManager.GetString("STR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string STR_RESTORE {
            get {
                return ResourceManager.GetString("STR_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string STR_YES {
            get {
                return ResourceManager.GetString("STR_YES", resourceCulture);
            }
        }
    }
}
