//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to find the tab file or the grid file?.
        /// </summary>
        internal static string ASK_LOCATE_TAB_FILE_OR_GRID_FILE {
            get {
                return ResourceManager.GetString("ASK_LOCATE_TAB_FILE_OR_GRID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to find the tab file or the raster file?.
        /// </summary>
        internal static string ASK_LOCATE_TAB_FILE_OR_RASTER_FILE {
            get {
                return ResourceManager.GetString("ASK_LOCATE_TAB_FILE_OR_RASTER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on/off auto locking of windows\nAuto lock window.
        /// </summary>
        internal static string BTN_HLP_AUTOLOCK_WINDOWS {
            get {
                return ResourceManager.GetString("BTN_HLP_AUTOLOCK_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone active window\nClone window.
        /// </summary>
        internal static string BTN_HLP_CLONE_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_CLONE_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close active window\nClose window.
        /// </summary>
        internal static string BTN_HLP_CLOSE_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_CLOSE_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock active window from closing\nLock window.
        /// </summary>
        internal static string BTN_HLP_LOCK_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_LOCK_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore closed window\nRestore closed window.
        /// </summary>
        internal static string BTN_HLP_RESTORE_CLOSED_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_RESTORE_CLOSED_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set preferred size and position on front window\nSet preferred size and position.
        /// </summary>
        internal static string BTN_HLP_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock active window from closing\nUnlock window.
        /// </summary>
        internal static string BTN_HLP_UNLOCK_FRONT_WINDOW {
            get {
                return ResourceManager.GetString("BTN_HLP_UNLOCK_FRONT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base windows ({0}).
        /// </summary>
        internal static string DLG_BASE_WINDOW_X {
            get {
                return ResourceManager.GetString("DLG_BASE_WINDOW_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Window.
        /// </summary>
        internal static string DLG_MODIFY_WINDOW {
            get {
                return ResourceManager.GetString("DLG_MODIFY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore windows.
        /// </summary>
        internal static string DLG_TTL_RESTORE_WINDOWS {
            get {
                return ResourceManager.GetString("DLG_TTL_RESTORE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick window to restore.
        /// </summary>
        internal static string DLG_TXT_PICK_WINDOW_TO_RESTORE {
            get {
                return ResourceManager.GetString("DLG_TXT_PICK_WINDOW_TO_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name of the new base window!.
        /// </summary>
        internal static string ERR_ENTER_NAME_FOR_NEW_BASE_WINDOW {
            get {
                return ResourceManager.GetString("ERR_ENTER_NAME_FOR_NEW_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active window must be a mapper window!.
        /// </summary>
        internal static string ERR_FRONT_WIN_NOT_MAPPER {
            get {
                return ResourceManager.GetString("ERR_FRONT_WIN_NOT_MAPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML is invalid!.
        /// </summary>
        internal static string ERR_INVALID_XML {
            get {
                return ResourceManager.GetString("ERR_INVALID_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The must be at least one window open!.
        /// </summary>
        internal static string ERR_NO_WIN_OPEN {
            get {
                return ResourceManager.GetString("ERR_NO_WIN_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no windows to restore!.
        /// </summary>
        internal static string ERR_NO_WINDOWS_TO_RESTORE {
            get {
                return ResourceManager.GetString("ERR_NO_WINDOWS_TO_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a window to read the size and position from!.
        /// </summary>
        internal static string ERR_OPEN_WINDOW_TO_READ_SIZE_POSITION {
            get {
                return ResourceManager.GetString("ERR_OPEN_WINDOW_TO_READ_SIZE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a window to resize and reposition!.
        /// </summary>
        internal static string ERR_OPEN_WINDOW_TO_RESIZE_REPOSITION {
            get {
                return ResourceManager.GetString("ERR_OPEN_WINDOW_TO_RESIZE_REPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a window to save to a workspace!.
        /// </summary>
        internal static string ERR_OPEN_WINDOW_TO_SAVE_TO_WOR {
            get {
                return ResourceManager.GetString("ERR_OPEN_WINDOW_TO_SAVE_TO_WOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the base window to update!.
        /// </summary>
        internal static string ERR_SELECT_BASE_WINDOW_TO_UPDATE {
            get {
                return ResourceManager.GetString("ERR_SELECT_BASE_WINDOW_TO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a non temporal layer in the Layer Control! .
        /// </summary>
        internal static string ERR_SELECT_NON_TEMPORAL_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_NON_TEMPORAL_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a normal layer!.
        /// </summary>
        internal static string ERR_SELECT_NORMAL_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_NORMAL_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a normal or raster/grid layer!.
        /// </summary>
        internal static string ERR_SELECT_NORMAL_OR_RASTER_OR_GRID_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_NORMAL_OR_RASTER_OR_GRID_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one layer in the Layer Control!.
        /// </summary>
        internal static string ERR_SELECT_ONE_LAYER_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_LAYER_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one map in the Layer Control!.
        /// </summary>
        internal static string ERR_SELECT_ONE_MAP_IN_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_MAP_IN_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one table in the TableList window!.
        /// </summary>
        internal static string ERR_SELECT_ONE_TABLE_IN_TABLE_LIST {
            get {
                return ResourceManager.GetString("ERR_SELECT_ONE_TABLE_IN_TABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Closed Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_ALL {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Browser Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_BROWSERS {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_BROWSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Layout Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_LAYOUTS {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_LAYOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Map Windows.
        /// </summary>
        internal static string LST_CLOSED_WINDOWS_MAPS {
            get {
                return ResourceManager.GetString("LST_CLOSED_WINDOWS_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Windows.
        /// </summary>
        internal static string LST_WINDOWS_ALL {
            get {
                return ResourceManager.GetString("LST_WINDOWS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Windows.
        /// </summary>
        internal static string LST_WINDOWS_BROWSERS {
            get {
                return ResourceManager.GetString("LST_WINDOWS_BROWSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Windows.
        /// </summary>
        internal static string LST_WINDOWS_LAYOUTS {
            get {
                return ResourceManager.GetString("LST_WINDOWS_LAYOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Windows.
        /// </summary>
        internal static string LST_WINDOWS_MAPS {
            get {
                return ResourceManager.GetString("LST_WINDOWS_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Windows.
        /// </summary>
        internal static string LST_WINDOWS_SPECIAL {
            get {
                return ResourceManager.GetString("LST_WINDOWS_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About {0}....
        /// </summary>
        internal static string MNU_ABOUT_PROGRAM_X {
            get {
                return ResourceManager.GetString("MNU_ABOUT_PROGRAM_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Table.
        /// </summary>
        internal static string MNU_CLOSE_TABLE {
            get {
                return ResourceManager.GetString("MNU_CLOSE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;End Program.
        /// </summary>
        internal static string MNU_END_PROGRAM {
            get {
                return ResourceManager.GetString("MNU_END_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MNU_HELP {
            get {
                return ResourceManager.GetString("MNU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autolock all windows.
        /// </summary>
        internal static string MNU_HLP_AUTOLOCK_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_HLP_AUTOLOCK_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone window.
        /// </summary>
        internal static string MNU_HLP_CLONE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_CLONE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the selected table.
        /// </summary>
        internal static string MNU_HLP_CLOSE_TABLE {
            get {
                return ResourceManager.GetString("MNU_HLP_CLOSE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        internal static string MNU_HLP_CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make window dockable.
        /// </summary>
        internal static string MNU_HLP_DOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_DOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a clone of the active layout.
        /// </summary>
        internal static string MNU_HLP_LAYOUT_CLONE_VIEW {
            get {
                return ResourceManager.GetString("MNU_HLP_LAYOUT_CLONE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds a file in Windows Explorer related to the selected table.
        /// </summary>
        internal static string MNU_HLP_LOCATE_FILE_IN_EXPLORER {
            get {
                return ResourceManager.GetString("MNU_HLP_LOCATE_FILE_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock window.
        /// </summary>
        internal static string MNU_HLP_LOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_LOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Window.
        /// </summary>
        internal static string MNU_HLP_MOFIFY_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_MOFIFY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the selected tab file in.
        /// </summary>
        internal static string MNU_HLP_OPEN_TABFILE_IN_TEXT_EDITOR {
            get {
                return ResourceManager.GetString("MNU_HLP_OPEN_TABFILE_IN_TEXT_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore one or more windows closed during this session.
        /// </summary>
        internal static string MNU_HLP_RESTORE_CLOSED_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_HLP_RESTORE_CLOSED_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore closed window.
        /// </summary>
        internal static string MNU_HLP_RESTORE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_RESTORE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Window Positions To The Saved State.
        /// </summary>
        internal static string MNU_HLP_RESTORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_HLP_RESTORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the active window to a workspace without the &apos;Open Table ...&apos; statements.
        /// </summary>
        internal static string MNU_HLP_SAVE_WINDOW_TO_WOR {
            get {
                return ResourceManager.GetString("MNU_HLP_SAVE_WINDOW_TO_WOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default view on all layers in map.
        /// </summary>
        internal static string MNU_HLP_SET_DEFAULT_VIEW_ALL_LAYERS {
            get {
                return ResourceManager.GetString("MNU_HLP_SET_DEFAULT_VIEW_ALL_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default view on selected layer.
        /// </summary>
        internal static string MNU_HLP_SET_DEFAULT_VIEW_SINGLE_LAYER {
            get {
                return ResourceManager.GetString("MNU_HLP_SET_DEFAULT_VIEW_SINGLE_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup base windows with size and position.
        /// </summary>
        internal static string MNU_HLP_SETUP_BASE_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_HLP_SETUP_BASE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which windows automatically to store positions of.
        /// </summary>
        internal static string MNU_HLP_STORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("MNU_HLP_STORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the current position of the windows.
        /// </summary>
        internal static string MNU_HLP_STORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_HLP_STORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore window positions when the program starts.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_RESTORE_WINDOWS_ON_START {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_RESTORE_WINDOWS_ON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically show the Layer Control window on startup.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_SHOW_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_SHOW_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically show the TableList window on startup.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_SHOW_TABLE_LIST {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_SHOW_TABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store window positions when the program ends.
        /// </summary>
        internal static string MNU_HLP_TOGGLE_STORE_WINDOWS_ON_EXIT {
            get {
                return ResourceManager.GetString("MNU_HLP_TOGGLE_STORE_WINDOWS_ON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock window.
        /// </summary>
        internal static string MNU_HLP_UNLOCK_WINDOW {
            get {
                return ResourceManager.GetString("MNU_HLP_UNLOCK_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zooms to the entire view of the layers map.
        /// </summary>
        internal static string MNU_HLP_VIEW_ENTIRE_MAP {
            get {
                return ResourceManager.GetString("MNU_HLP_VIEW_ENTIRE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to First.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_FIRST {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Last.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_LAST {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Next.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_NEXT {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Previous.
        /// </summary>
        internal static string MNU_HLP_ZOOM_TO_PREVIOUS {
            get {
                return ResourceManager.GetString("MNU_HLP_ZOOM_TO_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone View.
        /// </summary>
        internal static string MNU_LAYOUT_CLONE_VIEW {
            get {
                return ResourceManager.GetString("MNU_LAYOUT_CLONE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate File In Windows Explorer.
        /// </summary>
        internal static string MNU_LOCATE_FILE_IN_EXPLORER {
            get {
                return ResourceManager.GetString("MNU_LOCATE_FILE_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tab File In.
        /// </summary>
        internal static string MNU_OPEN_TABFILE_IN_TEXT_EDITOR {
            get {
                return ResourceManager.GetString("MNU_OPEN_TABFILE_IN_TEXT_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore Closed Window....
        /// </summary>
        internal static string MNU_RESTORE_CLOSED_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_RESTORE_CLOSED_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Window Positions Now.
        /// </summary>
        internal static string MNU_RESTORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_RESTORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Window To Workspace Without &apos;Open table ...&apos; statements.
        /// </summary>
        internal static string MNU_SAVE_WINDOW_TO_WOR {
            get {
                return ResourceManager.GetString("MNU_SAVE_WINDOW_TO_WOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default View On All Layers.
        /// </summary>
        internal static string MNU_SET_DEFAULT_VIEW_ALL_LAYERS {
            get {
                return ResourceManager.GetString("MNU_SET_DEFAULT_VIEW_ALL_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default View.
        /// </summary>
        internal static string MNU_SET_DEFAULT_VIEW_SINGLE_LAYER {
            get {
                return ResourceManager.GetString("MNU_SET_DEFAULT_VIEW_SINGLE_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Rreferred Size And Position On Front Window.
        /// </summary>
        internal static string MNU_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SET_WINDOW_SIZE_POSITION_USING_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Base Windows....
        /// </summary>
        internal static string MNU_SETUP_BASE_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_SETUP_BASE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;All Windows.
        /// </summary>
        internal static string MNU_SHOW_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("MNU_SHOW_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Info Window.
        /// </summary>
        internal static string MNU_SHOW_INFO_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_INFO_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Legend Window.
        /// </summary>
        internal static string MNU_SHOW_LEGEND_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_LEGEND_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The Map&amp;Basic Window.
        /// </summary>
        internal static string MNU_SHOW_MAPBASIC_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_MAPBASIC_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Message Window.
        /// </summary>
        internal static string MNU_SHOW_MESSAGE_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_MESSAGE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Ruler Window.
        /// </summary>
        internal static string MNU_SHOW_RULER_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_RULER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The &amp;Statistics Window.
        /// </summary>
        internal static string MNU_SHOW_STATISTICS_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_STATISTICS_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show Window.
        /// </summary>
        internal static string MNU_SHOW_WINDOW {
            get {
                return ResourceManager.GetString("MNU_SHOW_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Auto Store Position Of Windows.
        /// </summary>
        internal static string MNU_STORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("MNU_STORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Window Positions Now.
        /// </summary>
        internal static string MNU_STORE_WINDOWS_NOW {
            get {
                return ResourceManager.GetString("MNU_STORE_WINDOWS_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Window Positions On Startup.
        /// </summary>
        internal static string MNU_TOGGLE_RESTORE_WINDOWS_ON_START {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_RESTORE_WINDOWS_ON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Layer Control On Startup.
        /// </summary>
        internal static string MNU_TOGGLE_SHOW_LAYER_CONTROL {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_SHOW_LAYER_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;TableList On Startup.
        /// </summary>
        internal static string MNU_TOGGLE_SHOW_TABLE_LIST {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_SHOW_TABLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Window Positions On Exit.
        /// </summary>
        internal static string MNU_TOGGLE_STORE_WINDOWS_ON_EXIT {
            get {
                return ResourceManager.GetString("MNU_TOGGLE_STORE_WINDOWS_ON_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Entire Map.
        /// </summary>
        internal static string MNU_VIEW_ENTIRE_MAP {
            get {
                return ResourceManager.GetString("MNU_VIEW_ENTIRE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select workspace to save window to....
        /// </summary>
        internal static string PICK_WOR_TO_SAVE_WINDOW_TO {
            get {
                return ResourceManager.GetString("PICK_WOR_TO_SAVE_WINDOW_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowHelper can store size and position of windows on exit and restore these windows when it starts up next time. {\n}{\n}Do you want to turn this on?.
        /// </summary>
        internal static string QUEST_AUTOSTORE_WINDOW_POSITIONS {
            get {
                return ResourceManager.GetString("QUEST_AUTOSTORE_WINDOW_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to close this window: {0} ?.
        /// </summary>
        internal static string QUEST_CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("QUEST_CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string STR_APPLY {
            get {
                return ResourceManager.GetString("STR_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string STR_CHANGE {
            get {
                return ResourceManager.GetString("STR_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string STR_CLOSE {
            get {
                return ResourceManager.GetString("STR_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        internal static string STR_CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("STR_CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string STR_CREATE {
            get {
                return ResourceManager.GetString("STR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid File.
        /// </summary>
        internal static string STR_GRID_FILE {
            get {
                return ResourceManager.GetString("STR_GRID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string STR_HEIGHT {
            get {
                return ResourceManager.GetString("STR_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string STR_NAME {
            get {
                return ResourceManager.GetString("STR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New base window.
        /// </summary>
        internal static string STR_NEW_BASE_WINDOW {
            get {
                return ResourceManager.GetString("STR_NEW_BASE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string STR_NO {
            get {
                return ResourceManager.GetString("STR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string STR_OK {
            get {
                return ResourceManager.GetString("STR_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string STR_POSITION {
            get {
                return ResourceManager.GetString("STR_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster File.
        /// </summary>
        internal static string STR_RASTER_FILE {
            get {
                return ResourceManager.GetString("STR_RASTER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string STR_RESTORE {
            get {
                return ResourceManager.GetString("STR_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab File.
        /// </summary>
        internal static string STR_TAB_FILE {
            get {
                return ResourceManager.GetString("STR_TAB_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string STR_UPDATE {
            get {
                return ResourceManager.GetString("STR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Window Name.
        /// </summary>
        internal static string STR_USE_DEFAULT_WINDOW_NAME {
            get {
                return ResourceManager.GetString("STR_USE_DEFAULT_WINDOW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string STR_WIDTH {
            get {
                return ResourceManager.GetString("STR_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        internal static string STR_WINDOW_NAME {
            get {
                return ResourceManager.GetString("STR_WINDOW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string STR_X {
            get {
                return ResourceManager.GetString("STR_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string STR_Y {
            get {
                return ResourceManager.GetString("STR_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string STR_YES {
            get {
                return ResourceManager.GetString("STR_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string TAB_CLOSED {
            get {
                return ResourceManager.GetString("TAB_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string TAB_CURRENT {
            get {
                return ResourceManager.GetString("TAB_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string TAB_SPECIAL {
            get {
                return ResourceManager.GetString("TAB_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string VIEW_OF_VIEWS {
            get {
                return ResourceManager.GetString("VIEW_OF_VIEWS", resourceCulture);
            }
        }
    }
}
